name: Milestone Notifications

on:
  issues:
    types: [milestoned, demilestoned, closed]

jobs:
  notification:
    runs-on: ubuntu-latest
    steps:
    - name: Notify Slack
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      run: |
        curl -X POST --data-urlencode "payload={\"channel\": \"#my-channel-here\", \"username\": \"webhookbot\", \"text\": \"This is posted to #my-channel-here and comes from a bot named webhookbot.\", \"icon_emoji\": \":ghost:\"}" https://hooks.slack.com/services/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

