name: Milestone Mention

on:
  issues:
    types: [opened, edited, milestoned, demilestoned]
  pull_request:
    types: [opened, edited, milestoned, demilestoned]

jobs:
  mention:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Mention on Milestone Update
      run: |
        echo "Milestone updated! /cc @yourusername"
        # You'll need a custom script or action here to comment on the issue/PR
